### ISSUE TITLE
New config/env variables

### ISSUE THREAD

**Issue by iophobia** [x86dev/docker-ttrss#48] opened 2021-02-23 16:57 UTC
Seems like a [recent change](https://git.tt-rss.org/fox/tt-rss/wiki/GlobalConfig) to how config/env are read by TTRSS broke my setup or rather the connection to my postgre DB.

Browser now gives `Exception while creating PDO object:SQLSTATE[08006] [7] could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?`

And while I seemingly managed to get both to talk to each other in the BG (as seen by RAM/CPU usage of the images) by prefixing the DOCKER variables with the new "TTRSS_", the error remains. Any adjustments needed in your image? Sorry, not a coder.

**Comment by felixgilles** [comment] 2021-02-23 17:25
Same issue

**Comment by felixgilles** [comment] 2021-02-23 20:43
I have submit a PR #49 
It fixed the problem on my instance after editing the files directly in the docker 
```
docker exec -i -t yourdockercontainername /bin/sh -c ash
cd /srv
vi setup-ttrss.sh
vi ttrss-configure-db.php
```

**Comment by Thrilleratplay** [comment] 2021-02-24 05:31
@felixgilles I applied the changed in your PR to the respective files in the running docker container but the error persisted.  Even restarting the container did not help.  Did you make any other changes, maybe to the environment variable names?

**Comment by felixgilles** [comment] 2021-02-24 06:58
Yes sorry, I was a bit short.

I first pulled the last version of the docker image. Then I deleted the container and recreated it.
I also added in the dockerfile the environment key `TTRSS_PATH` with the value `/var/wwww/ttrss/`, because there is also an error on this variable (`setup-ttrss.sh` initializes it to `/var/www/ttrss` if not set, so the targeted config file is `/var/www/ttrssconfig`). 
Again, delete and recreate the container to take into account the modification (you can combine the two operations).
The modifications of the PR are of course to be redone afterwards.
You can see the result of the execution of `setup-ttrss.sh` by doing a docker logs, make sure that the modified file is `/var/www/ttrss/config`.

**Comment by P6g9YHK6** [comment] 2021-02-24 10:32
when can we expect a functional image to be released ? 
i suppose that everyone's installation just broke :/

**Comment by Thrilleratplay** [comment] 2021-02-24 14:08
@felixgilles I made a suggestion in the PR about including  `ENV TTRSS_PATH /var/www/ttrss/` in the Dockerfile.  With that, it works perfectly.  

Also, small typo, too many "w" in your previous comment for the TTRSS_PATH value.  For those who are copying and pasting before the caffeine kicks in, that is an easy things to miss.

**Comment by felixgilles** [comment] 2021-02-24 17:45
@Thrilleratplay Oops for the `wwww`. What happens when you write before you've even started your workday :-)

For the TTRSS_PATH I didn't modify because I don't know if it's better to put the / at the end by default (which obliges to modify all the uses of the variable in the setup), or if it's in the configuration of the base that I have to correct and remove the / at the end and only add it to the use of the concatenation with config.php
According to the opinion of @x86dev, I can make the modification in my PR before a merge.

**Comment by ionathanch** [comment] 2021-02-25 02:18
> I also added in the dockerfile the environment key `TTRSS_PATH` with the value `/var/wwww/ttrss/`, because there is also an error on this variable (`setup-ttrss.sh` initializes it to `/var/www/ttrss` if not set, so the targeted config file is `/var/www/ttrssconfig.php`).

It looks like this is because the file `ttrss-configure-db.php` sets its `$confpath` to `'/var/www/ttrss/'` by default and expects the path to already end with a trailing slash. I think it would be better to change this file to bring it in line with everywhere else:

```diff
diff --git a/root/srv/ttrss-configure-db.php b/root/srv/ttrss-configure-db.php
index 73895c7..fd1f0bd 100644
--- a/root/srv/ttrss-configure-db.php
+++ b/root/srv/ttrss-configure-db.php
@@ -6,2 +6,2 @@ include '/srv/ttrss-utils.php';
-$confpath = env('TTRSS_PATH', '/var/www/ttrss/');
-$conffile = $confpath . 'config.php';
+$confpath = env('TTRSS_PATH', '/var/www/ttrss');
+$conffile = $confpath . '/config.php';
@@ -76 +76 @@ catch (PDOException $e) {
-    $schema = file_get_contents($confpath . 'schema/ttrss_schema_' . $config['DB_TYPE'] . '.sql');
+    $schema = file_get_contents($confpath . '/schema/ttrss_schema_' . $config['DB_TYPE'] . '.sql');
```

**Comment by Thrilleratplay** [comment] 2021-02-25 05:09
Did anyone else have to rebuild the image after the rolling release reintroduced the issue?

**Comment by felixgilles** [comment] 2021-02-25 07:38
@Thrilleratplay not for me

**Comment by felixgilles** [comment] 2021-02-25 07:49
@ionathanch I agree with you, I think this is the best choice, setup-ttrss.sh is the leader, so ttrss-configure-db.php has to adapt, and this generates less change.
I have introduced your changes in my PR #49

**Comment by x86dev** [comment] 2021-02-25 08:00
Excellent work, Felix, thanks! Just as a heads-up, my installation broke as well, and I'm currently repairing and verifying PR #49 so that it can get merged into the master branch.

After that I'm building a new image for Docker Hub so that everyone can be up running again.

**Comment by felixgilles** [comment] 2021-02-25 08:24
:pray: @x86dev

**Comment by x86dev** [comment] 2021-02-25 08:30
Docker Hub's build d8848fda should contain Felix' PR #49, plus, while at it, also updated the Alpine base image to the latest available version for security reasons.

Please let me know if the build works for you all, so we can close the issue. Thanks!

**Comment by iophobia** [comment] 2021-02-25 09:56
Finally up and running again, thanks.

**Comment by bugwelle** [comment] 2021-02-25 10:06
I can confirm that it's working again. Thank you for fixing it! 🎉

**Comment by P6g9YHK6** [comment] 2021-02-26 01:17
I still have the issue even with a freshly created container is there something that i am missing ?

**Comment by cgi-cgi** [comment] 2021-02-26 07:09
@P6g9YHK6 I had the the issue with the latest image.
I checked logs of container and looks like it won't use `TTRSS_` env variables on startup scripts.
Adding `DB_` (duplicating) with credentials solved this problem for me.
![d6b4](https://user-images.githubusercontent.com/1552924/109267429-9d642180-781a-11eb-9e4d-a0c139fce252.png)

**Comment by P6g9YHK6** [comment] 2021-02-26 13:12
Solved thanks ! 

maybe an update to the documentation is required at this point. it's strting getting out of hands with all these variable.

**Comment by x86dev** [comment] 2021-02-26 16:59
> Solved thanks !
> 
> maybe an update to the documentation is required at this point. it's starting getting out of hands with all these variable.

Yes, that certainly would be very useful to have. No time for that at the moment though. Contributions are welcome :-)

So treating this issue as fixed. Please re-open if necessary.

**Closed by x86dev** 2021-02-26 16:59 UTC
